### ISSUE TITLE
"%.2f" usage in PO files

### ISSUE THREAD

**Issue by libreajans** [willkg/dennis#110] opened 2019-10-06 22:49 UTC
I think Dennis does not handle this kind (%.2f etc) usage correctly.

> %f is the format specifier used for float data type in the functions printf and scanf . By default it will display values upto 6 digits after the decimal point but , writing %.1f or %.2f will reduce the precision to 1 or 2 digits respectively.Hope that helps

https://www.quora.com/What-is-the-meaning-of-1f-2f-in-c

When I testing my GIMP translation It gave this warning:

**E104: bad format character: %.**

Actual code is here:

```
1154:#. value description and new value shown in the status bar
1155:#: ../app/actions/actions.c:617
1156:#, c-format
1157:msgid "%s: %.2f"
1158:msgstr "%s: %.2f"
```

**Comment by libreajans** [comment] 2019-10-06 23:04
I think these warnings are wrong too.

**E104: bad format character: %l**

```
12860:#: ../app/core/gimpbrush-load.c:254
12861:#, c-format
12862:msgid "Invalid header data in '%s': Brush name is too long: %lu"
12863:msgstr "'%s' içinde geçersiz başlık verisi: Fırça adı çok uzun: %lu"
```

**E104: bad format character: %-**
```
23441:#: ../app/tools/gimprotatetool.c:251
23442:#, c-format
23443:msgctxt "undo-type"
23444:msgid "Rotate by %-3.3g° around (%g, %g)"
23445:msgstr "Etrafında %-3.3g° ile döndür (%g, %g)"
```

**Comment by willkg** [comment] 2019-10-07 00:30
I suspect this is a duplicate of #58. Can you add information there for examples and test cases? Thank you!

**Closed by willkg** 2019-10-07 00:30 UTC
